name: CVPR-UGC-VQA
num_epochs: 3
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 8
num_workers: 6

wandb:
    project_name: VQA_Experiments_2025

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/CVPR_UGC/train/CVPR_UGC_train_artifacts.txt
            data_prefix: ../datasets/CVPR_UGC/UGC/
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1
    val-ugc:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/CVPR_UGC/test/CVPR_UGC_val_artifacts.txt
            data_prefix: ../datasets/CVPR_UGC/UGC/
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4

model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                checkpoint: false
                pretrained:
        backbone_size: swin_tiny_grpb
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64

optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05

load_path: ./pretrained_weights/swin_tiny_patch244_window877_kinetics400_1k.pth
test_load_path: ./pretrained_weights/val-UGC-artifacts_s_25_3_7.pth
